## Linear Algebra (numpy)

### numpy linalg module for operation on linear algebra

In [ ]:
import numpy as np

mat1 = np.arange(4).reshape(2,2)
mat2 = (np.arange(4)*2).reshape(2,2)
mat3 = (np.arange(4)*3).reshape(2,2)
# performing multiple dot product in a single function call
print(np.linalg.multi_dot( [mat1, mat2, mat3] ))
# [[ 36  66]
#  [132 234]] 
 


[[ 36  66]
 [132 234]]


### Solving system of linear equations

verifying if given system of linear equations has unique solutions, if solution exists , we find inverse and rank of the matrix

In [2]:
 
import numpy as np
a = np.array([[3, 1],[1, 2]])
b = np.array([9, 8])

# checking of system of linear equation as unique solution
print(np.linalg.det(a)) 
# 5.0

# here determinant is non-zero , so we have unique solution
print(np.linalg.solve(a, b))
# [ 2.  3.]

# matrix is also invertible as determinant is non-zero
print(np.linalg.inv(a))
# [[ 0.4 -0.2]
#  [-0.2  0.6]]

# calculating rank of the matrix
print(np.linalg.matrix_rank(a))
# 2 
 


5.000000000000001
[2. 3.]
[[ 0.4 -0.2]
 [-0.2  0.6]]
2
