## Additional Operations

3. Find out the cumulative sum of literacy rates by the end of every quarter each year. Find out the quarters for which this sum is greater or equal to 8.  

To find such quarters, we have to understand the significance of axis parameter. An axis parameter if equated to 0 implies that a function needs to be deployed across rows i.e. vertically. If in case axis parameter is equated to 1 then operation applies to columns.

In [2]:
import numpy as np 

S_X = np.array([[2, 5, 6, 5],
               [4, 8, 6, 5]])
print(S_X)
# [[2 5 6 5]
#  [4 8 6 5]]
S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])
print(S_Y)
# [[6 7 5 9]
#  [7 5 6 4]] 

[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]]


In [3]:

X_cumsum = np.cumsum(S_X, axis = 1)
print(X_cumsum)
# [[ 2  7 13 18]
#  [ 4 12 18 23]]
print( X_cumsum >= 8)
# [[False False  True  True]
#  [False  True  True  True]]
Y_cumsum = np.cumsum(S_Y, axis = 1)
print(Y_cumsum)
# [[ 6 13 18 27]
#  [ 7 12 18 22]]
print( Y_cumsum >= 8)
# [[False  True  True  True]
#  [False  True  True  True]] 
 


[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]
[[ 6 13 18 27]
 [ 7 12 18 22]]
[[False  True  True  True]
 [False  True  True  True]]


4. Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.


A concept much similar to the above, here we need to calculate mean of all quarters per year for State X. To achieve this, we find mean with axis = 1.

In [4]:
 
print(np.mean(S_X, axis = 1))
# [ 4.5   5.75]
 


[4.5  5.75]


To find mean of quarterly literacy rate for State Y, we find mean with axis = 0.

In [5]:
 
print(np.mean(S_Y, axis = 0))
# [ 6.5  6.   5.5  6.5]
 


[6.5 6.  5.5 6.5]
