In [3]:
import numpy as np

### Array Creation

In [4]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int32)

print(type(arr))
print(arr.dtype)
print(np.result_type(arr))

<class 'numpy.ndarray'>
int32
int32


In [6]:
print(np.arange(0, 30, 2.44, dtype=np.float64))

[ 0.    2.44  4.88  7.32  9.76 12.2  14.64 17.08 19.52 21.96 24.4  26.84
 29.28]


In [7]:
print(np.linspace(0, 1, 5, dtype=np.float64))

[0.   0.25 0.5  0.75 1.  ]


## Matrix Creation

### Using numpy array to form Matrix

In [9]:
m = np.array([1, 2, 4, 5, 6, 7]).reshape(2, 3)
m

array([[1, 2, 4],
       [5, 6, 7]])

### Using numpy's built in matrix function

In [11]:
m = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
m

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

### Using other functions

In [12]:
print(np.eye(3)) # Identity matrix
# [[ 1.  0.  0.]
#  [ 0.  1.  0.]
#  [ 0.  0.  1.]]
print( np.zeros( (4,3) ) )
# [[ 0.  0.  0.]
#  [ 0.  0.  0.]
#  [ 0.  0.  0.]
#  [ 0.  0.  0.]]
print(np.ones( (3,3), dtype = np.float64 ))
# [[ 1.  1.  1.]
#  [ 1.  1.  1.]
#  [ 1.  1.  1.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [16]:
arr = np.arange(4)
arr.reshape(2,2)
print(arr.shape)


(4,)


In [15]:
arr = np.arange(4).reshape(4,-1)
print(arr.shape)

(4, 1)
