## vectorized Operations

Suppose we're given a literacy rate data sample of State X and State Y for two consecutive years measured quarterly on a scale of 0-10. Let us try to arrive at the following outcomes:

--> Quarterly difference between each state's literacy rate per year.

--> Quarters having a literacy rate less than 2.

--> Find out the cumulative sum of literacy rates by the end of every quarter each year. Find out the quarters for which this sum is greater or equal to 8.  

--> Mean of each year's literacy rate of State X and mean of each quarterly's literacy rate of State Y.


In [3]:
import numpy as np

In [4]:
 
S_X = np.array([[2, 5, 6, 5],
               [4, 8, 6, 5]])
print(S_X)
# [[2 5 6 5]
#  [4 8 6 5]]
S_Y = np.array([[6, 7, 5, 9],
               [7, 5, 6, 4]])
print(S_Y)
# [[6 7 5 9]
#  [7 5 6 4]] 
 


[[2 5 6 5]
 [4 8 6 5]]
[[6 7 5 9]
 [7 5 6 4]]


In [5]:
# Quarterly difference between each state's literacy rate per year

print(S_Y - S_X)

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [9]:
# Quarters Having a literacy rate less than 2

print(S_Y < 2)
print(S_X < 2)


''' Method 2 '''
twos_mat = np.ones((2, 4)) * 2
print(np.less(S_Y, twos_mat))
# [[False False False False]
#  [False False False False]] 

[[False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]]
[[False False False False]
 [False False False False]]
